FROM node:12

RUN mkdir -p /home/app
WORKDIR /home/app

COPY package.json ./

RUN apt-get install -y wget
#    && apt-get install -y build-essential \
#    &&  
#&& rm -rf /var/lib/apt/lists/*

# Install miniconda
ENV CONDA_DIR /opt/conda
RUN wget --quiet https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O ~/miniconda.sh \
    && /bin/sh ~./miniconda.sh -b -p /opt/conda

# Put conda in path so we can use conda activate
ENV PATH=$CONDA_DIR/bin:$PATH

RUN npm install

EXPOSE 3000

CMD ["nodemon", "index.js"]